In [1]:
import pandas as pd

In [2]:
oil_data = pd.read_csv("CrudeOIlPrices_Texas.csv")
oil_data.head()

  observation_date  DCOILWTICO
0       2021-03-30       60.55
1       2021-03-31       59.19
2       2021-04-01       61.41
3       2021-04-02         NaN
4       2021-04-05       58.73

In [3]:
cpi_data = pd.read_csv("Consumer_Price_Index.csv")
cpi_data.head()

  observation_date  CPALTT01USM657N
0       1955-02-01              0.0
1       1955-03-01              0.0
2       1955-04-01              0.0
3       1955-05-01              0.0
4       1955-06-01              0.0

In [5]:
oil_data.isnull().sum()

observation_date     0
DCOILWTICO          56
dtype: int64

In [6]:
cpi_data.isnull().sum()

observation_date    0
CPALTT01USM657N     0
dtype: int64

In [7]:
avg_price = oil_data['DCOILWTICO'].mean()
oil_data_clean = oil_data.fillna({'DCOILWTICO': avg_price})

In [13]:
oil_data.columns = ['DATE', 'OIL_PRICE']
cpi_data.columns = ['DATE', 'CPI']

In [17]:
oil_mean = oil_data['OIL_PRICE'].mean()
oil_min = oil_data['OIL_PRICE'].min()
oil_max = oil_data['OIL_PRICE'].max()
oil_median = oil_data['OIL_PRICE'].median()
oil_std = oil_data['OIL_PRICE'].std()
print(oil_mean)
print(oil_min)
print(oil_max)
print(oil_median)
print(oil_std)

77.21844675740593
55.44
123.64
75.03
12.820987663547518

In [18]:
cpi_mean = cpi_data['CPI'].mean()
cpi_min = cpi_data['CPI'].min()
cpi_max = cpi_data['CPI'].max()
cpi_median = cpi_data['CPI'].median()
cpi_std = cpi_data['CPI'].std()

print(cpi_mean)
print(cpi_min)
print(cpi_max)
print(cpi_median)
print(cpi_std)

0.2973834891894962
-1.9152895328595805
1.80586907449211
0.29055444645697703
0.3558606076134019